version: '3'
services:
  # Database service
  database:
    image: mariadb:latest
    container_name: my_mariadb_db
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - my_network

  # Microservice 1
  auth:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "3001:3001"
    networks:
      - my_network

  # Microservice 2
  offer-management:
    build:
      context: ./offer-management
    container_name: offer-management
    ports:
      - "3002:3002"
    networks:
      - my_network

  # Microservice 3
  order-management:
    build:
      context: ./order-management
    container_name: order-management
    ports:
      - "3003:3003"
    networks:
      - my_network

  # Microservice 3
  product-management:
    build:
      context: ./product-management
    container_name: product-management
    ports:
      - "3004:3004"
    networks:
      - my_network
    env_file: .env
    environment:
      MYSQL_TCP_HOST: host.docker.internal

networks:
  my_network: