version: '3'
services:
#   Database service

  auth-database:
    image: mariadb:latest
    container_name: auth_database
    env_file: .env
    ports:
      - "3301:3306"
    networks:
      - my_network

  offer-management-database:
    image: mariadb:latest
    container_name: offer_management_database
    env_file: .env
    ports:
      - "3302:3306"
    networks:
      - my_network

  order-management-database:
    image: mariadb:latest
    container_name: order_management_database
    env_file: .env
    ports:
      - "3303:3306"
    networks:
      - my_network

  product-management-database:
    image: mariadb:latest
    container_name: product_management_database
    env_file: .env
    ports:
      - "3304:3306"
    networks:
      - my_network

  # Microservice 1
  auth:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "3001:3001"
    networks:
      - my_network
    depends_on:
      - auth-database

  # Microservice 2
  offer-management:
    build:
      context: ./offer-management
    container_name: offer-management
    ports:
      - "3002:3002"
    networks:
      - my_network
    depends_on:
      - offer-management-database

  # Microservice 3
  order-management:
    build:
      context: ./order-management
    container_name: order-management
    ports:
      - "3003:3003"
    networks:
      - my_network
    depends_on:
      - order-management-database

  # Microservice 3
  product-management:
    build:
      context: ./product-management
    container_name: product-management
    ports:
      - "3004:3004"
    networks:
      - my_network
    depends_on:
      - product-management-database

networks:
  my_network: