version: '3'

services:

  #   Database service
  user-microservice-database:
    image: mariadb:latest
    container_name: user_microservice_database
    env_file:
      - user-microservice/.env
    ports:
      - "3301:3306"
    networks:
      - my_network
    volumes:
      - user-data:/var/lib/mysql

  offer-management-database:
    image: mariadb:latest
    container_name: offer_management_database
    env_file:
      - offer-management/.env
    ports:
      - "3302:3306"
    networks:
      - my_network
    volumes:
      - offer-data:/var/lib/mysql

  order-microservice-database:
    image: mariadb:latest
    container_name: order_microservice_database
    env_file:
      - order-microservice/.env
    ports:
      - "3303:3306"
    networks:
      - my_network
    volumes:
      - order-data:/var/lib/mysql

  product-management-database:
    image: mariadb:latest
    container_name: product_management_database
    env_file:
      - product-management/.env
    ports:
      - "3304:3306"
    networks:
      - my_network
    volumes:
      - product-data:/var/lib/mysql

  offer-microservice-database:
    image: mariadb:latest
    container_name: offer-microservice_database
    env_file:
      - offer-microservice/.env
    ports:
      - "3305:3306"
    networks:
      - my_network
    volumes:
      - offer-data:/var/lib/mysql

  # Microservice 1
  user-microservice:
    build:
      context: user-microservice
    container_name: user-microservice
    ports:
      - "3001:3001"
    env_file:
      - user-microservice/.env
    networks:
      - my_network
    depends_on:
      - user-microservice-database
    restart: on-failure

  # Microservice 2
  offer-management:
    build:
      context: ./offer-management
    container_name: offer-management
    ports:
      - "3002:3002"
    env_file:
      - offer-management/.env
    networks:
      - my_network
    depends_on:
      - offer-management-database
    restart: on-failure

  # Microservice 3
  order-microservice:
    build:
      context: order-microservice
    container_name: order-microservice
    ports:
      - "3003:3003"
    env_file:
      - order-microservice/.env
    networks:
      - my_network
    depends_on:
      - order-microservice-database
    restart: on-failure

  # Microservice 4
  product-management:
    build:
      context: ./product-management
    container_name: product-management
    ports:
      - "3004:3004"
    env_file:
      - product-management/.env
    networks:
      - my_network
    depends_on:
      - product-management-database
    restart: on-failure

  # Microservice 5
  offer-microservice:
    build:
      context: ./offer-microservice
    container_name: offer-microservice
    ports:
      - "3005:3005"
    env_file:
      - offer-microservice/.env
    networks:
      - my_network
    depends_on:
      - offer-microservice-database
    restart: on-failure

networks:
  my_network:

volumes:
  user-data:
  offer-data:
  order-data:
  product-data: